default_platform(:ios)

platform :ios do
  desc "Build a signed IPA for sideloading"
  lane :build_sideload do
    build_app(
      workspace: "ios/UFitness.xcworkspace",
      scheme: "UFitness",
      export_method: "development",
      skip_profile_detection: true,
      # These flags force Xcode to skip the "Team" requirement
      xcargs: "CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY='' CODE_SIGN_ENTITLEMENTS='' GCC_OPTIMIZATION_LEVEL=0",
      export_options: {
        method: "development",
        signingStyle: "manual"
      }
    )
  end
end