default_platform(:ios)

platform :ios do
  desc "Build a signed IPA for sideloading"
  lane :build_sideload do
    # Point Fastlane to the workspace created by expo prebuild
    build_app(
      workspace: "ios/UFitness.xcworkspace", # Usually named after your project
      scheme: "UFitness",
      export_method: "development",
      skip_profile_detection: true,
      export_options: {
        method: "development",
        signingStyle: "manual"
      }
    )
  end
end